### ISSUE TITLE
[Calculate Similarity] Can we not using sentence-transformers pre-trained?

### ISSUE THREAD

**Issue by lacls** [jamescalam/transformers#2]
Hi there,

I so appreciate your nice work, It did give me a lot more understanding about the tokenization of the BERT model.

So in my case of training on the Vietnamese language (with a bunch of new specific vocabularies), can I load the model, not from sentence-transformer pre-trained ([here the model I intend to use](https://huggingface.co/vinai/phobert-large))

I did give it a shot, below is my pseudo-code
```
model_name = "vinai/phobert-large"
model = AutoModel.from_pretrained(model_name)
tokenizer = AutoTokenizer.from_pretrained(model_name)
sentences = [
    "tôi thích quán này dữ lắm lắm luôn á trời",
    "trời hôm nay đẹp lắm",
]
#the first sentence means: I extremely love this restaurant, 
#while the second one is the today's sky is so nice
#_______________

# initialize dictionary to store tokenized sentences
tokens = {'input_ids': [], 'attention_mask': []}

for sentence in sentences:
    # encode each sentence and append to dictionary
    new_tokens = tokenizer.encode_plus(clean_doc(sentence), max_length=128,
                                       truncation=True, padding='max_length',
                                       return_tensors='pt')
    tokens['input_ids'].append(new_tokens['input_ids'][0])
    tokens['attention_mask'].append(new_tokens['attention_mask'][0])

# reformat list of tensors into single tensor
tokens['input_ids'] = torch.stack(tokens['input_ids'])
tokens['attention_mask'] = torch.stack(tokens['attention_mask'])
outputs = model(**tokens)

embeddings = outputs.last_hidden_state

attention_mask = tokens['attention_mask']
mask = attention_mask.unsqueeze(-1).expand(embeddings.size()).float()

masked_embeddings = embeddings * mask
summed = torch.sum(masked_embeddings, 1)
summed_mask = torch.clamp(mask.sum(1), min=1e-9)
mean_pooled = summed / summed_mask

from sklearn.metrics.pairwise import cosine_similarity
mean_pooled = mean_pooled.detach().numpy()
cosine_similarity(
    [mean_pooled[0]],
    mean_pooled[1:]
)
```
Particularly, these two sentences are quite different, but their cosine value is about 91%.

Or there is any approach more suitable in my case.

I do appreciate your time and sharing.

**Comment by jamescalam** [comment]
Hey @lacls, apologies for the late response. Your code looks good, I think the problem most likely is that the PhoBERT model will not be trained specifically for similarity, whereas the sentence-transformer models are, so they will naturally outperform PhoBERT.

Nonetheless, I would hope that we could still get reasonable results using PhoBERT, maybe the cosine value is very high here, it could be an anomaly though. Have you tried with many sentences? I'd recommend getting 20 or so sentences with varying similarities and testing those.

Otherwise, it would be worth looking into if/how we could fine-tune a model like PhoBERT to be better suited for similarity, I can't say I have experience with this _yet_, although it is something I plan to work on soon.

Let me know if you manage to get results from more sentences :)

**Comment by lacls** [comment]
I do really appreciate your response.

I will update the results with more diverse sentences.

And I really agree with you at the point that, the PhoBERT wasn't be trained specifically for similarity.

I also intend to test these two sentences with a multilingual pre-trained of sentence-transformer to really know what was going on.

**Comment by jamescalam** [comment]
Yes definitely give that a go! Only thing I would check is which languages the multilingual models cover - the models I've seen I remember covering Chinese, English, German, and a couple others - but I'm not sure about Vietnamese.

I did find [this article](https://towardsdatascience.com/a-complete-guide-to-transfer-learning-from-english-to-other-languages-using-sentence-embeddings-8c427f8804a9) which looks pretty interesting and might help, the relevant part for this begins under the **Transfer learning sentence embedding** header - maybe this could help :)

**Comment by lacls** [comment]
Thank you really much for your sharing <3.

**Comment by jamescalam** [comment]
Closing the issue as I think you found your solution 😄
